/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.scoping;

import uniandes.mdd.aplicacion.blockchain.scoping.AbstractBlockchainScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BlockchainScopeProvider extends AbstractBlockchainScopeProvider {
}
