<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="blockchain" nsURI="http://www.example.org/blockchain" nsPrefix="blockchain">
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smartcontract" upperBound="-1"
        eType="#//SmartContract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" upperBound="-1"
        eType="#//TipoDato" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartContract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operaciones" upperBound="-1"
        eType="#//Operacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estado" lowerBound="1"
        upperBound="-1" eType="#//Estado" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//Parametro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esUserDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retorno" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineas" upperBound="-1"
        eType="#//Linea" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Estado" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentencia" abstract="true" interface="true"
      eSuperTypes="#//Linea"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionLogica" eSuperTypes="#//ExpresionBinaria">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operador" eType="#//OperadorLogico"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primitivo" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//DatoPrimitivo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDato" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperadorLogico">
    <eLiterals name="IGUAL_IGUAL" literal="=="/>
    <eLiterals name="DIFERENTE" value="1" literal="!="/>
    <eLiterals name="MAYORQUE" value="2" literal=">"/>
    <eLiterals name="MENORQUE" value="3" literal="&lt;"/>
    <eLiterals name="MAYORIGUAL" value="4" literal=">="/>
    <eLiterals name="MENORIGUAL" value="5" literal="&lt;="/>
    <eLiterals name="AND" value="7" literal="&amp;&amp;"/>
    <eLiterals name="OR" value="8" literal="||"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operador">
    <eLiterals name="MAS" literal="+"/>
    <eLiterals name="MENOS" value="1" literal="-"/>
    <eLiterals name="PRODUCTO" value="2" literal="*"/>
    <eLiterals name="DIVISION" value="3" literal="/"/>
    <eLiterals name="IGUAL" value="4" literal="="/>
    <eLiterals name="GET" value="5"/>
    <eLiterals name="DELETE" value="6"/>
    <eLiterals name="PUT" value="7" literal="PUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionAritmetica" eSuperTypes="#//ExpresionBinaria">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operador" eType="#//Operador"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Sentencia #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatoPrimitivo">
    <eLiterals name="STRING" literal="String"/>
    <eLiterals name="NUMERICO" value="1" literal="uint"/>
    <eLiterals name="BOOLEAN" value="2" literal="false"/>
    <eLiterals name="ADDRESS" value="3" literal="address"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapa" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoDatoKey" lowerBound="1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoDatoValue" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expresionlogica" lowerBound="1"
        eType="#//ExpresionLogica" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineas" upperBound="-1"
        eType="#//Linea" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseLines" eType="#//Else"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expresion" abstract="true" interface="true"
      eSuperTypes="#//Linea"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionNumerica" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionTexto" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionBoolean" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionReferenciada" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencia" lowerBound="1"
        eType="#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionRelacional" eSuperTypes="#//ExpresionBinaria">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operadorRelacional" eType="#//OperadorRelacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperadorRelacion">
    <eLiterals name="PUNTO" literal="."/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionBinaria" abstract="true" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="izq" lowerBound="1" eType="#//Expresion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="der" lowerBound="1" eType="#//Expresion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Linea" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Else">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineas" upperBound="-1"
        eType="#//Linea" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Retorno" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineaRetorno" upperBound="-1"
        eType="#//Linea" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
