<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="blockchain" nsURI="http://www.example.org/blockchain" nsPrefix="blockchain">
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smartcontract" upperBound="-1"
        eType="#//SmartContract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" upperBound="-1"
        eType="#//TipoDato" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartContract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operaciones" upperBound="-1"
        eType="#//Operacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estado" lowerBound="1"
        upperBound="-1" eType="#//Estado" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//Parametro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencia" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retorno" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esUserDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Estado" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentencia" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionLogica" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operador" eType="#//OperadorLogico"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Retorno" eSuperTypes="#//Sentencia"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primitivo" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//DatoPrimitivo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDato" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OperadorLogico">
    <eLiterals name="IGUAL_IGUAL"/>
    <eLiterals name="DIFERENTE" value="1"/>
    <eLiterals name="MAYORQUE" value="2"/>
    <eLiterals name="MENORQUE" value="3"/>
    <eLiterals name="MAYORIGUAL" value="4"/>
    <eLiterals name="MENORIGUAL" value="5"/>
    <eLiterals name="PUNTO" value="6"/>
    <eLiterals name="AND" value="7"/>
    <eLiterals name="OR" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operador">
    <eLiterals name="MAS"/>
    <eLiterals name="MENOS" value="1"/>
    <eLiterals name="PRODUCTO" value="2"/>
    <eLiterals name="DIVISION" value="3"/>
    <eLiterals name="IGUAL" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionAritmetica" eSuperTypes="#//Expresion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operador" eType="#//Operador"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatoPrimitivo">
    <eLiterals name="STRING"/>
    <eLiterals name="NUMERICO" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seq" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoDatoKey" lowerBound="1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoDatoValue" lowerBound="1"
        eType="#//TipoDato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condicional" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoCondicional" eType="#//TipoCondicion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expresionlogica" lowerBound="1"
        upperBound="-1" eType="#//ExpresionLogica" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoCondicion">
    <eLiterals name="IF"/>
    <eLiterals name="ELSE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expresion" abstract="true" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladoIzq" lowerBound="1"
        eType="#//Sentencia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladoDer" lowerBound="1"
        eType="#//Sentencia"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValorElementos" abstract="true" eSuperTypes="#//Sentencia"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionNumerica" eSuperTypes="#//ValorElementos">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionTexto" eSuperTypes="#//ValorElementos">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionBoolean" eSuperTypes="#//ValorElementos">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpresionReferenciada" eSuperTypes="#//ValorElementos">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipodato" eType="#//TipoDato"/>
  </eClassifiers>
</ecore:EPackage>
