/*
 * generated by Xtext 2.12.0
 */
package org.xtext.blockchain.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.blockchain.MyDslRuntimeModule
import org.xtext.blockchain.MyDslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
