/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.validation;

import uniandes.mdd.aplicacion.blockchain.validation.AbstractBlockchainValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BlockchainValidator extends AbstractBlockchainValidator {
}
