/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BlockchainStandaloneSetup extends BlockchainStandaloneSetupGenerated {

	def static void doSetup() {
		new BlockchainStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
