/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uniandes.mdd.aplicacion.blockchain.ui.internal.BlockchainActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlockchainExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BlockchainActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BlockchainActivator.getInstance().getInjector(BlockchainActivator.UNIANDES_MDD_APLICACION_BLOCKCHAIN_BLOCKCHAIN);
	}
	
}
