/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl.ui.internal.MydslActivator;

public class BlockchainUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("uniandes.mdd.aplicacion.blockchain.Blockchain");
	}

}
