/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ui.contentassist;

import uniandes.mdd.aplicacion.blockchain.ui.contentassist.AbstractBlockchainProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BlockchainProposalProvider extends AbstractBlockchainProposalProvider {
}
