/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BlockchainUiModule /* implements AbstractBlockchainUiModule  */{
}
