/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BlockchainIdeModule /* implements AbstractBlockchainIdeModule  */{
}
