/**
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.ide;

import uniandes.mdd.aplicacion.blockchain.ide.AbstractBlockchainIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BlockchainIdeModule extends AbstractBlockchainIdeModule {
}
