/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BlockchainGrammarAccess extends AbstractGrammarElementFinder {
	
	public class AplicacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Aplicacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAplicacionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAplicacionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cSmartcontractAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cSmartcontractSmartContractParserRuleCall_4_0_0 = (RuleCall)cSmartcontractAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cSmartcontractAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cSmartcontractSmartContractParserRuleCall_4_1_1_0 = (RuleCall)cSmartcontractAssignment_4_1_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTipoDatoKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTipodatoAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTipodatoTipoDatoParserRuleCall_5_1_0 = (RuleCall)cTipodatoAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cTipodatoAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cTipodatoTipoDatoParserRuleCall_5_2_1_0 = (RuleCall)cTipodatoAssignment_5_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Aplicacion:
		//	{Aplicacion}
		//	'Aplicacion'
		//	name=EString
		//	'{' (smartcontract+=SmartContract ("," smartcontract+=SmartContract)*)? ('TipoDato' tipodato+=TipoDato (","
		//	tipodato+=TipoDato)*)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Aplicacion} 'Aplicacion' name=EString '{' (smartcontract+=SmartContract ("," smartcontract+=SmartContract)*)?
		//('TipoDato' tipodato+=TipoDato ("," tipodato+=TipoDato)*)* '}'
		public Group getGroup() { return cGroup; }
		
		//{Aplicacion}
		public Action getAplicacionAction_0() { return cAplicacionAction_0; }
		
		//'Aplicacion'
		public Keyword getAplicacionKeyword_1() { return cAplicacionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(smartcontract+=SmartContract ("," smartcontract+=SmartContract)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//smartcontract+=SmartContract
		public Assignment getSmartcontractAssignment_4_0() { return cSmartcontractAssignment_4_0; }
		
		//SmartContract
		public RuleCall getSmartcontractSmartContractParserRuleCall_4_0_0() { return cSmartcontractSmartContractParserRuleCall_4_0_0; }
		
		//("," smartcontract+=SmartContract)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//smartcontract+=SmartContract
		public Assignment getSmartcontractAssignment_4_1_1() { return cSmartcontractAssignment_4_1_1; }
		
		//SmartContract
		public RuleCall getSmartcontractSmartContractParserRuleCall_4_1_1_0() { return cSmartcontractSmartContractParserRuleCall_4_1_1_0; }
		
		//('TipoDato' tipodato+=TipoDato ("," tipodato+=TipoDato)*)*
		public Group getGroup_5() { return cGroup_5; }
		
		//'TipoDato'
		public Keyword getTipoDatoKeyword_5_0() { return cTipoDatoKeyword_5_0; }
		
		//tipodato+=TipoDato
		public Assignment getTipodatoAssignment_5_1() { return cTipodatoAssignment_5_1; }
		
		//TipoDato
		public RuleCall getTipodatoTipoDatoParserRuleCall_5_1_0() { return cTipodatoTipoDatoParserRuleCall_5_1_0; }
		
		//("," tipodato+=TipoDato)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//","
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }
		
		//tipodato+=TipoDato
		public Assignment getTipodatoAssignment_5_2_1() { return cTipodatoAssignment_5_2_1; }
		
		//TipoDato
		public RuleCall getTipodatoTipoDatoParserRuleCall_5_2_1_0() { return cTipodatoTipoDatoParserRuleCall_5_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TipoDatoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.TipoDato");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEntidadParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPrimitivoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMapaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//TipoDato:
		//	Entidad | Primitivo | Mapa;
		@Override public ParserRule getRule() { return rule; }
		
		//Entidad | Primitivo | Mapa
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Entidad
		public RuleCall getEntidadParserRuleCall_0() { return cEntidadParserRuleCall_0; }
		
		//Primitivo
		public RuleCall getPrimitivoParserRuleCall_1() { return cPrimitivoParserRuleCall_1; }
		
		//Mapa
		public RuleCall getMapaParserRuleCall_2() { return cMapaParserRuleCall_2; }
	}
	public class SentenciaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Sentencia");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParametroParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEstadoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cExpresionLogicaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cExpresionAritmeticaParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cVariableParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cCondicionalParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cExpresionNumericaParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cEStringParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cEBooleanParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cExpresionReferenciadaParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cExpresionRelacionalParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		
		//Sentencia:
		//	Parametro | Estado | ExpresionLogica | ExpresionAritmetica | Variable | Condicional | ExpresionNumerica | EString |
		//	EBoolean | ExpresionReferenciada | ExpresionRelacional;
		@Override public ParserRule getRule() { return rule; }
		
		//Parametro | Estado | ExpresionLogica | ExpresionAritmetica | Variable | Condicional | ExpresionNumerica | EString |
		//EBoolean | ExpresionReferenciada | ExpresionRelacional
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Parametro
		public RuleCall getParametroParserRuleCall_0() { return cParametroParserRuleCall_0; }
		
		//Estado
		public RuleCall getEstadoParserRuleCall_1() { return cEstadoParserRuleCall_1; }
		
		//ExpresionLogica
		public RuleCall getExpresionLogicaParserRuleCall_2() { return cExpresionLogicaParserRuleCall_2; }
		
		//ExpresionAritmetica
		public RuleCall getExpresionAritmeticaParserRuleCall_3() { return cExpresionAritmeticaParserRuleCall_3; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_4() { return cVariableParserRuleCall_4; }
		
		//Condicional
		public RuleCall getCondicionalParserRuleCall_5() { return cCondicionalParserRuleCall_5; }
		
		//ExpresionNumerica
		public RuleCall getExpresionNumericaParserRuleCall_6() { return cExpresionNumericaParserRuleCall_6; }
		
		//EString
		public RuleCall getEStringParserRuleCall_7() { return cEStringParserRuleCall_7; }
		
		//EBoolean
		public RuleCall getEBooleanParserRuleCall_8() { return cEBooleanParserRuleCall_8; }
		
		//ExpresionReferenciada
		public RuleCall getExpresionReferenciadaParserRuleCall_9() { return cExpresionReferenciadaParserRuleCall_9; }
		
		//ExpresionRelacional
		public RuleCall getExpresionRelacionalParserRuleCall_10() { return cExpresionRelacionalParserRuleCall_10; }
	}
	public class SmartContractElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.SmartContract");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSmartContractKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cEntidadesAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cEntidadesEntidadParserRuleCall_3_0_0 = (RuleCall)cEntidadesAssignment_3_0.eContents().get(0);
		private final Assignment cEntidadesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cEntidadesEntidadParserRuleCall_3_1_0 = (RuleCall)cEntidadesAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cEstadoAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cEstadoEstadoParserRuleCall_4_0_0 = (RuleCall)cEstadoAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cEstadoAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cEstadoEstadoParserRuleCall_4_1_1_0 = (RuleCall)cEstadoAssignment_4_1_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cOperacionesAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cOperacionesOperacionParserRuleCall_5_0_0 = (RuleCall)cOperacionesAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cOperacionesAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cOperacionesOperacionParserRuleCall_5_1_1_0 = (RuleCall)cOperacionesAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SmartContract:
		//	'SmartContract'
		//	name=EString
		//	'{' (entidades+=Entidad entidades+=Entidad*)* (estado+=Estado ("," estado+=Estado)*)* (operaciones+=Operacion (","
		//	operaciones+=Operacion)*)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SmartContract' name=EString '{' (entidades+=Entidad entidades+=Entidad*)* (estado+=Estado ("," estado+=Estado)*)*
		//(operaciones+=Operacion ("," operaciones+=Operacion)*)* '}'
		public Group getGroup() { return cGroup; }
		
		//'SmartContract'
		public Keyword getSmartContractKeyword_0() { return cSmartContractKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(entidades+=Entidad entidades+=Entidad*)*
		public Group getGroup_3() { return cGroup_3; }
		
		//entidades+=Entidad
		public Assignment getEntidadesAssignment_3_0() { return cEntidadesAssignment_3_0; }
		
		//Entidad
		public RuleCall getEntidadesEntidadParserRuleCall_3_0_0() { return cEntidadesEntidadParserRuleCall_3_0_0; }
		
		//entidades+=Entidad*
		public Assignment getEntidadesAssignment_3_1() { return cEntidadesAssignment_3_1; }
		
		//Entidad
		public RuleCall getEntidadesEntidadParserRuleCall_3_1_0() { return cEntidadesEntidadParserRuleCall_3_1_0; }
		
		//(estado+=Estado ("," estado+=Estado)*)*
		public Group getGroup_4() { return cGroup_4; }
		
		//estado+=Estado
		public Assignment getEstadoAssignment_4_0() { return cEstadoAssignment_4_0; }
		
		//Estado
		public RuleCall getEstadoEstadoParserRuleCall_4_0_0() { return cEstadoEstadoParserRuleCall_4_0_0; }
		
		//("," estado+=Estado)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//estado+=Estado
		public Assignment getEstadoAssignment_4_1_1() { return cEstadoAssignment_4_1_1; }
		
		//Estado
		public RuleCall getEstadoEstadoParserRuleCall_4_1_1_0() { return cEstadoEstadoParserRuleCall_4_1_1_0; }
		
		//(operaciones+=Operacion ("," operaciones+=Operacion)*)*
		public Group getGroup_5() { return cGroup_5; }
		
		//operaciones+=Operacion
		public Assignment getOperacionesAssignment_5_0() { return cOperacionesAssignment_5_0; }
		
		//Operacion
		public RuleCall getOperacionesOperacionParserRuleCall_5_0_0() { return cOperacionesOperacionParserRuleCall_5_0_0; }
		
		//("," operaciones+=Operacion)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//operaciones+=Operacion
		public Assignment getOperacionesAssignment_5_1_1() { return cOperacionesAssignment_5_1_1; }
		
		//Operacion
		public RuleCall getOperacionesOperacionParserRuleCall_5_1_1_0() { return cOperacionesOperacionParserRuleCall_5_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EntidadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Entidad");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntidadAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntidadKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cAtributosAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cAtributosAtributoParserRuleCall_4_0_0 = (RuleCall)cAtributosAssignment_4_0.eContents().get(0);
		private final Assignment cAtributosAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAtributosAtributoParserRuleCall_4_1_0 = (RuleCall)cAtributosAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Entidad:
		//	{Entidad}
		//	'Entidad'
		//	name=EString
		//	'{' (atributos+=Atributo atributos+=Atributo*)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Entidad} 'Entidad' name=EString '{' (atributos+=Atributo atributos+=Atributo*)* '}'
		public Group getGroup() { return cGroup; }
		
		//{Entidad}
		public Action getEntidadAction_0() { return cEntidadAction_0; }
		
		//'Entidad'
		public Keyword getEntidadKeyword_1() { return cEntidadKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(atributos+=Atributo atributos+=Atributo*)*
		public Group getGroup_4() { return cGroup_4; }
		
		//atributos+=Atributo
		public Assignment getAtributosAssignment_4_0() { return cAtributosAssignment_4_0; }
		
		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_4_0_0() { return cAtributosAtributoParserRuleCall_4_0_0; }
		
		//atributos+=Atributo*
		public Assignment getAtributosAssignment_4_1() { return cAtributosAssignment_4_1; }
		
		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_4_1_0() { return cAtributosAtributoParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class OperacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Operacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperacionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperacionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIsUdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cEsUserDefinedAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cEsUserDefinedEBooleanParserRuleCall_2_1_0 = (RuleCall)cEsUserDefinedAssignment_2_1.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cParametrosAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cParametrosParametroParserRuleCall_5_0_0 = (RuleCall)cParametrosAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cParametrosAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cParametrosParametroParserRuleCall_5_1_1_0 = (RuleCall)cParametrosAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cColonKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRetornoAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cRetornoTipoDatoCrossReference_7_1_0 = (CrossReference)cRetornoAssignment_7_1.eContents().get(0);
		private final RuleCall cRetornoTipoDatoEStringParserRuleCall_7_1_0_1 = (RuleCall)cRetornoTipoDatoCrossReference_7_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cReturnKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cSentenciaAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final RuleCall cSentenciaSentenciaParserRuleCall_10_0_0 = (RuleCall)cSentenciaAssignment_10_0.eContents().get(0);
		private final Assignment cSentenciaAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cSentenciaSentenciaParserRuleCall_10_1_0 = (RuleCall)cSentenciaAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Operacion:
		//	{Operacion}
		//	'Operacion' ('isUd=' esUserDefined?=EBoolean)+
		//	name=EString
		//	'(' (parametros+=Parametro ("," parametros+=Parametro)*)?
		//	')' (':' retorno=[TipoDato|EString])?
		//	'{'
		//	'return'? (sentencia+=Sentencia sentencia+=Sentencia*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Operacion} 'Operacion' ('isUd=' esUserDefined?=EBoolean)+ name=EString '(' (parametros+=Parametro (","
		//parametros+=Parametro)*)? ')' (':' retorno=[TipoDato|EString])? '{' 'return'? (sentencia+=Sentencia
		//sentencia+=Sentencia*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Operacion}
		public Action getOperacionAction_0() { return cOperacionAction_0; }
		
		//'Operacion'
		public Keyword getOperacionKeyword_1() { return cOperacionKeyword_1; }
		
		//('isUd=' esUserDefined?=EBoolean)+
		public Group getGroup_2() { return cGroup_2; }
		
		//'isUd='
		public Keyword getIsUdKeyword_2_0() { return cIsUdKeyword_2_0; }
		
		//esUserDefined?=EBoolean
		public Assignment getEsUserDefinedAssignment_2_1() { return cEsUserDefinedAssignment_2_1; }
		
		//EBoolean
		public RuleCall getEsUserDefinedEBooleanParserRuleCall_2_1_0() { return cEsUserDefinedEBooleanParserRuleCall_2_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//(parametros+=Parametro ("," parametros+=Parametro)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//parametros+=Parametro
		public Assignment getParametrosAssignment_5_0() { return cParametrosAssignment_5_0; }
		
		//Parametro
		public RuleCall getParametrosParametroParserRuleCall_5_0_0() { return cParametrosParametroParserRuleCall_5_0_0; }
		
		//("," parametros+=Parametro)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//parametros+=Parametro
		public Assignment getParametrosAssignment_5_1_1() { return cParametrosAssignment_5_1_1; }
		
		//Parametro
		public RuleCall getParametrosParametroParserRuleCall_5_1_1_0() { return cParametrosParametroParserRuleCall_5_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//(':' retorno=[TipoDato|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//':'
		public Keyword getColonKeyword_7_0() { return cColonKeyword_7_0; }
		
		//retorno=[TipoDato|EString]
		public Assignment getRetornoAssignment_7_1() { return cRetornoAssignment_7_1; }
		
		//[TipoDato|EString]
		public CrossReference getRetornoTipoDatoCrossReference_7_1_0() { return cRetornoTipoDatoCrossReference_7_1_0; }
		
		//EString
		public RuleCall getRetornoTipoDatoEStringParserRuleCall_7_1_0_1() { return cRetornoTipoDatoEStringParserRuleCall_7_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//'return'?
		public Keyword getReturnKeyword_9() { return cReturnKeyword_9; }
		
		//(sentencia+=Sentencia sentencia+=Sentencia*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//sentencia+=Sentencia
		public Assignment getSentenciaAssignment_10_0() { return cSentenciaAssignment_10_0; }
		
		//Sentencia
		public RuleCall getSentenciaSentenciaParserRuleCall_10_0_0() { return cSentenciaSentenciaParserRuleCall_10_0_0; }
		
		//sentencia+=Sentencia*
		public Assignment getSentenciaAssignment_10_1() { return cSentenciaAssignment_10_1; }
		
		//Sentencia
		public RuleCall getSentenciaSentenciaParserRuleCall_10_1_0() { return cSentenciaSentenciaParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EstadoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Estado");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEstadoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTipodatoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTipodatoTipoDatoCrossReference_1_0 = (CrossReference)cTipodatoAssignment_1.eContents().get(0);
		private final RuleCall cTipodatoTipoDatoIDTerminalRuleCall_1_0_1 = (RuleCall)cTipodatoTipoDatoCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Estado:
		//	'Estado'
		//	tipodato=[TipoDato] name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Estado' tipodato=[TipoDato] name=EString
		public Group getGroup() { return cGroup; }
		
		//'Estado'
		public Keyword getEstadoKeyword_0() { return cEstadoKeyword_0; }
		
		//tipodato=[TipoDato]
		public Assignment getTipodatoAssignment_1() { return cTipodatoAssignment_1; }
		
		//[TipoDato]
		public CrossReference getTipodatoTipoDatoCrossReference_1_0() { return cTipodatoTipoDatoCrossReference_1_0; }
		
		//ID
		public RuleCall getTipodatoTipoDatoIDTerminalRuleCall_1_0_1() { return cTipodatoTipoDatoIDTerminalRuleCall_1_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class AtributoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Atributo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTipodatoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTipodatoTipoDatoCrossReference_0_0 = (CrossReference)cTipodatoAssignment_0.eContents().get(0);
		private final RuleCall cTipodatoTipoDatoEStringParserRuleCall_0_0_1 = (RuleCall)cTipodatoTipoDatoCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Atributo:
		//	tipodato=[TipoDato|EString] name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//tipodato=[TipoDato|EString] name=EString
		public Group getGroup() { return cGroup; }
		
		//tipodato=[TipoDato|EString]
		public Assignment getTipodatoAssignment_0() { return cTipodatoAssignment_0; }
		
		//[TipoDato|EString]
		public CrossReference getTipodatoTipoDatoCrossReference_0_0() { return cTipodatoTipoDatoCrossReference_0_0; }
		
		//EString
		public RuleCall getTipodatoTipoDatoEStringParserRuleCall_0_0_1() { return cTipodatoTipoDatoEStringParserRuleCall_0_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class ParametroElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Parametro");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTipodatoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTipodatoTipoDatoCrossReference_0_0 = (CrossReference)cTipodatoAssignment_0.eContents().get(0);
		private final RuleCall cTipodatoTipoDatoEStringParserRuleCall_0_0_1 = (RuleCall)cTipodatoTipoDatoCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Parametro:
		//	tipodato=[TipoDato|EString] name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//tipodato=[TipoDato|EString] name=EString
		public Group getGroup() { return cGroup; }
		
		//tipodato=[TipoDato|EString]
		public Assignment getTipodatoAssignment_0() { return cTipodatoAssignment_0; }
		
		//[TipoDato|EString]
		public CrossReference getTipodatoTipoDatoCrossReference_0_0() { return cTipodatoTipoDatoCrossReference_0_0; }
		
		//EString
		public RuleCall getTipodatoTipoDatoEStringParserRuleCall_0_0_1() { return cTipodatoTipoDatoEStringParserRuleCall_0_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class ExpresionLogicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionLogica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpLogKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Assignment cLadoIzqAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cLadoIzqSentenciaCrossReference_3_0 = (CrossReference)cLadoIzqAssignment_3.eContents().get(0);
		private final RuleCall cLadoIzqSentenciaEStringParserRuleCall_3_0_1 = (RuleCall)cLadoIzqSentenciaCrossReference_3_0.eContents().get(1);
		private final Assignment cOperadorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperadorOperadorLogicoEnumRuleCall_4_0 = (RuleCall)cOperadorAssignment_4.eContents().get(0);
		private final Assignment cLadoDerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cLadoDerSentenciaCrossReference_5_0 = (CrossReference)cLadoDerAssignment_5.eContents().get(0);
		private final RuleCall cLadoDerSentenciaEStringParserRuleCall_5_0_1 = (RuleCall)cLadoDerSentenciaCrossReference_5_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ExpresionLogica:
		//	'ExpLog'
		//	'('? ('id' id=EInt)?
		//	ladoIzq=[Sentencia|EString] operador=OperadorLogico+
		//	ladoDer=[Sentencia|EString] ')'?;
		@Override public ParserRule getRule() { return rule; }
		
		//'ExpLog' '('? ('id' id=EInt)? ladoIzq=[Sentencia|EString] operador=OperadorLogico+ ladoDer=[Sentencia|EString] ')'?
		public Group getGroup() { return cGroup; }
		
		//'ExpLog'
		public Keyword getExpLogKeyword_0() { return cExpLogKeyword_0; }
		
		//'('?
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//('id' id=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EInt
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_1_0() { return cIdEIntParserRuleCall_2_1_0; }
		
		//ladoIzq=[Sentencia|EString]
		public Assignment getLadoIzqAssignment_3() { return cLadoIzqAssignment_3; }
		
		//[Sentencia|EString]
		public CrossReference getLadoIzqSentenciaCrossReference_3_0() { return cLadoIzqSentenciaCrossReference_3_0; }
		
		//EString
		public RuleCall getLadoIzqSentenciaEStringParserRuleCall_3_0_1() { return cLadoIzqSentenciaEStringParserRuleCall_3_0_1; }
		
		//operador=OperadorLogico+
		public Assignment getOperadorAssignment_4() { return cOperadorAssignment_4; }
		
		//OperadorLogico
		public RuleCall getOperadorOperadorLogicoEnumRuleCall_4_0() { return cOperadorOperadorLogicoEnumRuleCall_4_0; }
		
		//ladoDer=[Sentencia|EString]
		public Assignment getLadoDerAssignment_5() { return cLadoDerAssignment_5; }
		
		//[Sentencia|EString]
		public CrossReference getLadoDerSentenciaCrossReference_5_0() { return cLadoDerSentenciaCrossReference_5_0; }
		
		//EString
		public RuleCall getLadoDerSentenciaEStringParserRuleCall_5_0_1() { return cLadoDerSentenciaEStringParserRuleCall_5_0_1; }
		
		//')'?
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class ExpresionAritmeticaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionAritmetica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionAritmeticaAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cIdKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cIdAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_1_1_0 = (RuleCall)cIdAssignment_1_1.eContents().get(0);
		private final Assignment cLadoIzqAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cLadoIzqSentenciaCrossReference_2_0 = (CrossReference)cLadoIzqAssignment_2.eContents().get(0);
		private final RuleCall cLadoIzqSentenciaEStringParserRuleCall_2_0_1 = (RuleCall)cLadoIzqSentenciaCrossReference_2_0.eContents().get(1);
		private final Assignment cOperadorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperadorOperadorEnumRuleCall_3_0 = (RuleCall)cOperadorAssignment_3.eContents().get(0);
		private final Assignment cLadoDerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cLadoDerSentenciaCrossReference_4_0 = (CrossReference)cLadoDerAssignment_4.eContents().get(0);
		private final RuleCall cLadoDerSentenciaEStringParserRuleCall_4_0_1 = (RuleCall)cLadoDerSentenciaCrossReference_4_0.eContents().get(1);
		
		//ExpresionAritmetica:
		//	{ExpresionAritmetica} ('id' id=EInt)?
		//	ladoIzq=[Sentencia|EString] operador=Operador+
		//	ladoDer=[Sentencia|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{ExpresionAritmetica} ('id' id=EInt)? ladoIzq=[Sentencia|EString] operador=Operador+ ladoDer=[Sentencia|EString]
		public Group getGroup() { return cGroup; }
		
		//{ExpresionAritmetica}
		public Action getExpresionAritmeticaAction_0() { return cExpresionAritmeticaAction_0; }
		
		//('id' id=EInt)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'id'
		public Keyword getIdKeyword_1_0() { return cIdKeyword_1_0; }
		
		//id=EInt
		public Assignment getIdAssignment_1_1() { return cIdAssignment_1_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_1_1_0() { return cIdEIntParserRuleCall_1_1_0; }
		
		//ladoIzq=[Sentencia|EString]
		public Assignment getLadoIzqAssignment_2() { return cLadoIzqAssignment_2; }
		
		//[Sentencia|EString]
		public CrossReference getLadoIzqSentenciaCrossReference_2_0() { return cLadoIzqSentenciaCrossReference_2_0; }
		
		//EString
		public RuleCall getLadoIzqSentenciaEStringParserRuleCall_2_0_1() { return cLadoIzqSentenciaEStringParserRuleCall_2_0_1; }
		
		//operador=Operador+
		public Assignment getOperadorAssignment_3() { return cOperadorAssignment_3; }
		
		//Operador
		public RuleCall getOperadorOperadorEnumRuleCall_3_0() { return cOperadorOperadorEnumRuleCall_3_0; }
		
		//ladoDer=[Sentencia|EString]
		public Assignment getLadoDerAssignment_4() { return cLadoDerAssignment_4; }
		
		//[Sentencia|EString]
		public CrossReference getLadoDerSentenciaCrossReference_4_0() { return cLadoDerSentenciaCrossReference_4_0; }
		
		//EString
		public RuleCall getLadoDerSentenciaEStringParserRuleCall_4_0_1() { return cLadoDerSentenciaEStringParserRuleCall_4_0_1; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTipodatoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTipodatoTipoDatoCrossReference_1_0 = (CrossReference)cTipodatoAssignment_1.eContents().get(0);
		private final RuleCall cTipodatoTipoDatoEStringParserRuleCall_1_0_1 = (RuleCall)cTipodatoTipoDatoCrossReference_1_0.eContents().get(1);
		private final Keyword cVarKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		
		//Variable:
		//	{Variable} tipodato=[TipoDato|EString]
		//	'var'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable} tipodato=[TipoDato|EString] 'var' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//tipodato=[TipoDato|EString]
		public Assignment getTipodatoAssignment_1() { return cTipodatoAssignment_1; }
		
		//[TipoDato|EString]
		public CrossReference getTipodatoTipoDatoCrossReference_1_0() { return cTipodatoTipoDatoCrossReference_1_0; }
		
		//EString
		public RuleCall getTipodatoTipoDatoEStringParserRuleCall_1_0_1() { return cTipodatoTipoDatoEStringParserRuleCall_1_0_1; }
		
		//'var'
		public Keyword getVarKeyword_2() { return cVarKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
	}
	public class CondicionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Condicional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCondicionalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTipoCondicionalKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTipoCondicionalAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTipoCondicionalTipoCondicionEnumRuleCall_2_1_0 = (RuleCall)cTipoCondicionalAssignment_2_1.eContents().get(0);
		private final Keyword cExpresionlogicaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpresionlogicaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpresionlogicaExpresionLogicaParserRuleCall_4_0 = (RuleCall)cExpresionlogicaAssignment_4.eContents().get(0);
		private final Keyword cSentenciasKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSentenciasAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSentenciasSentenciaParserRuleCall_7_0 = (RuleCall)cSentenciasAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cSentenciasAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cSentenciasSentenciaParserRuleCall_8_1_0 = (RuleCall)cSentenciasAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cElseKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cElseAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cElseCondicionalParserRuleCall_10_2_0 = (RuleCall)cElseAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cElseAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cElseCondicionalParserRuleCall_10_3_1_0 = (RuleCall)cElseAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Condicional:
		//	'Condicional'
		//	'{' ('tipoCondicional' tipoCondicional=TipoCondicion)?
		//	'expresionlogica' expresionlogica=ExpresionLogica
		//	'sentencias' '{' sentencias+=Sentencia ("," sentencias+=Sentencia)* '}' ('else' '{' else+=Condicional (","
		//	else+=Condicional)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Condicional' '{' ('tipoCondicional' tipoCondicional=TipoCondicion)? 'expresionlogica' expresionlogica=ExpresionLogica
		//'sentencias' '{' sentencias+=Sentencia ("," sentencias+=Sentencia)* '}' ('else' '{' else+=Condicional (","
		//else+=Condicional)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Condicional'
		public Keyword getCondicionalKeyword_0() { return cCondicionalKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('tipoCondicional' tipoCondicional=TipoCondicion)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'tipoCondicional'
		public Keyword getTipoCondicionalKeyword_2_0() { return cTipoCondicionalKeyword_2_0; }
		
		//tipoCondicional=TipoCondicion
		public Assignment getTipoCondicionalAssignment_2_1() { return cTipoCondicionalAssignment_2_1; }
		
		//TipoCondicion
		public RuleCall getTipoCondicionalTipoCondicionEnumRuleCall_2_1_0() { return cTipoCondicionalTipoCondicionEnumRuleCall_2_1_0; }
		
		//'expresionlogica'
		public Keyword getExpresionlogicaKeyword_3() { return cExpresionlogicaKeyword_3; }
		
		//expresionlogica=ExpresionLogica
		public Assignment getExpresionlogicaAssignment_4() { return cExpresionlogicaAssignment_4; }
		
		//ExpresionLogica
		public RuleCall getExpresionlogicaExpresionLogicaParserRuleCall_4_0() { return cExpresionlogicaExpresionLogicaParserRuleCall_4_0; }
		
		//'sentencias'
		public Keyword getSentenciasKeyword_5() { return cSentenciasKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//sentencias+=Sentencia
		public Assignment getSentenciasAssignment_7() { return cSentenciasAssignment_7; }
		
		//Sentencia
		public RuleCall getSentenciasSentenciaParserRuleCall_7_0() { return cSentenciasSentenciaParserRuleCall_7_0; }
		
		//("," sentencias+=Sentencia)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//sentencias+=Sentencia
		public Assignment getSentenciasAssignment_8_1() { return cSentenciasAssignment_8_1; }
		
		//Sentencia
		public RuleCall getSentenciasSentenciaParserRuleCall_8_1_0() { return cSentenciasSentenciaParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//('else' '{' else+=Condicional ("," else+=Condicional)* '}')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'else'
		public Keyword getElseKeyword_10_0() { return cElseKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//else+=Condicional
		public Assignment getElseAssignment_10_2() { return cElseAssignment_10_2; }
		
		//Condicional
		public RuleCall getElseCondicionalParserRuleCall_10_2_0() { return cElseCondicionalParserRuleCall_10_2_0; }
		
		//("," else+=Condicional)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//else+=Condicional
		public Assignment getElseAssignment_10_3_1() { return cElseAssignment_10_3_1; }
		
		//Condicional
		public RuleCall getElseCondicionalParserRuleCall_10_3_1_0() { return cElseCondicionalParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ExpresionNumericaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionNumerica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionNumericaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExpNumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueEDoubleParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//ExpresionNumerica:
		//	{ExpresionNumerica}
		//	'ExpNum'
		//	value=EDouble?;
		@Override public ParserRule getRule() { return rule; }
		
		//{ExpresionNumerica} 'ExpNum' value=EDouble?
		public Group getGroup() { return cGroup; }
		
		//{ExpresionNumerica}
		public Action getExpresionNumericaAction_0() { return cExpresionNumericaAction_0; }
		
		//'ExpNum'
		public Keyword getExpNumKeyword_1() { return cExpNumKeyword_1; }
		
		//value=EDouble?
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_2_0() { return cValueEDoubleParserRuleCall_2_0; }
	}
	public class ExpresionTextoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionTexto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionTextoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExpTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ExpresionTexto:
		//	{ExpresionTexto}
		//	'ExpText'
		//	'{' ('value' value=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExpresionTexto} 'ExpText' '{' ('value' value=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{ExpresionTexto}
		public Action getExpresionTextoAction_0() { return cExpresionTextoAction_0; }
		
		//'ExpText'
		public Keyword getExpTextKeyword_1() { return cExpTextKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ExpresionBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionBoolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionBooleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValueValueKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		private final Keyword cExpBoolKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExpresionBoolean:
		//	{ExpresionBoolean} value?='value'?
		//	'ExpBool';
		@Override public ParserRule getRule() { return rule; }
		
		//{ExpresionBoolean} value?='value'? 'ExpBool'
		public Group getGroup() { return cGroup; }
		
		//{ExpresionBoolean}
		public Action getExpresionBooleanAction_0() { return cExpresionBooleanAction_0; }
		
		//value?='value'?
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//'value'
		public Keyword getValueValueKeyword_1_0() { return cValueValueKeyword_1_0; }
		
		//'ExpBool'
		public Keyword getExpBoolKeyword_2() { return cExpBoolKeyword_2; }
	}
	public class ExpresionReferenciadaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionReferenciada");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionReferenciadaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExpRefKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Assignment cEntReferenciadaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cEntReferenciadaEntidadCrossReference_3_0 = (CrossReference)cEntReferenciadaAssignment_3.eContents().get(0);
		private final RuleCall cEntReferenciadaEntidadEStringParserRuleCall_3_0_1 = (RuleCall)cEntReferenciadaEntidadCrossReference_3_0.eContents().get(1);
		private final Assignment cAtrReferenciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cAtrReferenciadoAtributoCrossReference_4_0 = (CrossReference)cAtrReferenciadoAssignment_4.eContents().get(0);
		private final RuleCall cAtrReferenciadoAtributoEStringParserRuleCall_4_0_1 = (RuleCall)cAtrReferenciadoAtributoCrossReference_4_0.eContents().get(1);
		
		//ExpresionReferenciada:
		//	{ExpresionReferenciada}
		//	'ExpRef' ('id' id=EInt)?
		//	entReferenciada=[Entidad|EString]?
		//	atrReferenciado=[Atributo|EString]?;
		@Override public ParserRule getRule() { return rule; }
		
		//{ExpresionReferenciada} 'ExpRef' ('id' id=EInt)? entReferenciada=[Entidad|EString]? atrReferenciado=[Atributo|EString]?
		public Group getGroup() { return cGroup; }
		
		//{ExpresionReferenciada}
		public Action getExpresionReferenciadaAction_0() { return cExpresionReferenciadaAction_0; }
		
		//'ExpRef'
		public Keyword getExpRefKeyword_1() { return cExpRefKeyword_1; }
		
		//('id' id=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EInt
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_1_0() { return cIdEIntParserRuleCall_2_1_0; }
		
		//entReferenciada=[Entidad|EString]?
		public Assignment getEntReferenciadaAssignment_3() { return cEntReferenciadaAssignment_3; }
		
		//[Entidad|EString]
		public CrossReference getEntReferenciadaEntidadCrossReference_3_0() { return cEntReferenciadaEntidadCrossReference_3_0; }
		
		//EString
		public RuleCall getEntReferenciadaEntidadEStringParserRuleCall_3_0_1() { return cEntReferenciadaEntidadEStringParserRuleCall_3_0_1; }
		
		//atrReferenciado=[Atributo|EString]?
		public Assignment getAtrReferenciadoAssignment_4() { return cAtrReferenciadoAssignment_4; }
		
		//[Atributo|EString]
		public CrossReference getAtrReferenciadoAtributoCrossReference_4_0() { return cAtrReferenciadoAtributoCrossReference_4_0; }
		
		//EString
		public RuleCall getAtrReferenciadoAtributoEStringParserRuleCall_4_0_1() { return cAtrReferenciadoAtributoEStringParserRuleCall_4_0_1; }
	}
	public class ExpresionRelacionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.ExpresionRelacional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpRelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Assignment cLadoIzqAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cLadoIzqSentenciaCrossReference_3_0 = (CrossReference)cLadoIzqAssignment_3.eContents().get(0);
		private final RuleCall cLadoIzqSentenciaEStringParserRuleCall_3_0_1 = (RuleCall)cLadoIzqSentenciaCrossReference_3_0.eContents().get(1);
		private final Assignment cOperadorRelacionalAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperadorRelacionalOperadorRelacionEnumRuleCall_4_0 = (RuleCall)cOperadorRelacionalAssignment_4.eContents().get(0);
		private final Assignment cLadoDerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cLadoDerSentenciaCrossReference_5_0 = (CrossReference)cLadoDerAssignment_5.eContents().get(0);
		private final RuleCall cLadoDerSentenciaEStringParserRuleCall_5_0_1 = (RuleCall)cLadoDerSentenciaCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ExpresionRelacional:
		//	'ExpRel'
		//	'{' ('id' id=EInt)?
		//	ladoIzq=[Sentencia|EString] operadorRelacional=OperadorRelacion?
		//	ladoDer=[Sentencia|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ExpRel' '{' ('id' id=EInt)? ladoIzq=[Sentencia|EString] operadorRelacional=OperadorRelacion?
		//ladoDer=[Sentencia|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'ExpRel'
		public Keyword getExpRelKeyword_0() { return cExpRelKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('id' id=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'id'
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }
		
		//id=EInt
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_1_0() { return cIdEIntParserRuleCall_2_1_0; }
		
		//ladoIzq=[Sentencia|EString]
		public Assignment getLadoIzqAssignment_3() { return cLadoIzqAssignment_3; }
		
		//[Sentencia|EString]
		public CrossReference getLadoIzqSentenciaCrossReference_3_0() { return cLadoIzqSentenciaCrossReference_3_0; }
		
		//EString
		public RuleCall getLadoIzqSentenciaEStringParserRuleCall_3_0_1() { return cLadoIzqSentenciaEStringParserRuleCall_3_0_1; }
		
		//operadorRelacional=OperadorRelacion?
		public Assignment getOperadorRelacionalAssignment_4() { return cOperadorRelacionalAssignment_4; }
		
		//OperadorRelacion
		public RuleCall getOperadorRelacionalOperadorRelacionEnumRuleCall_4_0() { return cOperadorRelacionalOperadorRelacionEnumRuleCall_4_0; }
		
		//ladoDer=[Sentencia|EString]
		public Assignment getLadoDerAssignment_5() { return cLadoDerAssignment_5; }
		
		//[Sentencia|EString]
		public CrossReference getLadoDerSentenciaCrossReference_5_0() { return cLadoDerSentenciaCrossReference_5_0; }
		
		//EString
		public RuleCall getLadoDerSentenciaEStringParserRuleCall_5_0_1() { return cLadoDerSentenciaEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class PrimitivoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Primitivo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPrimitivoAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTipoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTipoDatoPrimitivoEnumRuleCall_1_0 = (RuleCall)cTipoAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Primitivo:
		//	{Primitivo} tipo=DatoPrimitivo+
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Primitivo} tipo=DatoPrimitivo+ name=EString
		public Group getGroup() { return cGroup; }
		
		//{Primitivo}
		public Action getPrimitivoAction_0() { return cPrimitivoAction_0; }
		
		//tipo=DatoPrimitivo+
		public Assignment getTipoAssignment_1() { return cTipoAssignment_1; }
		
		//DatoPrimitivo
		public RuleCall getTipoDatoPrimitivoEnumRuleCall_1_0() { return cTipoDatoPrimitivoEnumRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class MapaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Mapa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMapKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLessThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTipoDatoKeyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTipoDatoKeyTipoDatoCrossReference_4_0 = (CrossReference)cTipoDatoKeyAssignment_4.eContents().get(0);
		private final RuleCall cTipoDatoKeyTipoDatoEStringParserRuleCall_4_0_1 = (RuleCall)cTipoDatoKeyTipoDatoCrossReference_4_0.eContents().get(1);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTipoDatoValueAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTipoDatoValueTipoDatoCrossReference_6_0 = (CrossReference)cTipoDatoValueAssignment_6.eContents().get(0);
		private final RuleCall cTipoDatoValueTipoDatoEStringParserRuleCall_6_0_1 = (RuleCall)cTipoDatoValueTipoDatoCrossReference_6_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Mapa:
		//	name=EString
		//	':' 'Map'
		//	'<'
		//	tipoDatoKey=[TipoDato|EString]
		//	',' tipoDatoValue=[TipoDato|EString] '>';
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ':' 'Map' '<' tipoDatoKey=[TipoDato|EString] ',' tipoDatoValue=[TipoDato|EString] '>'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'Map'
		public Keyword getMapKeyword_2() { return cMapKeyword_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_3() { return cLessThanSignKeyword_3; }
		
		//tipoDatoKey=[TipoDato|EString]
		public Assignment getTipoDatoKeyAssignment_4() { return cTipoDatoKeyAssignment_4; }
		
		//[TipoDato|EString]
		public CrossReference getTipoDatoKeyTipoDatoCrossReference_4_0() { return cTipoDatoKeyTipoDatoCrossReference_4_0; }
		
		//EString
		public RuleCall getTipoDatoKeyTipoDatoEStringParserRuleCall_4_0_1() { return cTipoDatoKeyTipoDatoEStringParserRuleCall_4_0_1; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//tipoDatoValue=[TipoDato|EString]
		public Assignment getTipoDatoValueAssignment_6() { return cTipoDatoValueAssignment_6; }
		
		//[TipoDato|EString]
		public CrossReference getTipoDatoValueTipoDatoCrossReference_6_0() { return cTipoDatoValueTipoDatoCrossReference_6_0; }
		
		//EString
		public RuleCall getTipoDatoValueTipoDatoEStringParserRuleCall_6_0_1() { return cTipoDatoValueTipoDatoEStringParserRuleCall_6_0_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_7() { return cGreaterThanSignKeyword_7; }
	}
	
	public class OperadorLogicoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.OperadorLogico");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cIGUAL_IGUALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cIGUAL_IGUALEqualsSignEqualsSignKeyword_0_0 = (Keyword)cIGUAL_IGUALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDIFERENTEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDIFERENTEExclamationMarkEqualsSignKeyword_1_0 = (Keyword)cDIFERENTEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMAYORQUEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMAYORQUEGreaterThanSignKeyword_2_0 = (Keyword)cMAYORQUEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMENORQUEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMENORQUELessThanSignKeyword_3_0 = (Keyword)cMENORQUEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMAYORIGUALEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMAYORIGUALGreaterThanSignEqualsSignKeyword_4_0 = (Keyword)cMAYORIGUALEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMENORIGUALEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMENORIGUALLessThanSignEqualsSignKeyword_5_0 = (Keyword)cMENORIGUALEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cANDAmpersandAmpersandKeyword_6_0 = (Keyword)cANDEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cORVerticalLineVerticalLineKeyword_7_0 = (Keyword)cOREnumLiteralDeclaration_7.eContents().get(0);
		
		//enum OperadorLogico:
		//	IGUAL_IGUAL='==' | DIFERENTE='!=' | MAYORQUE='>' | MENORQUE='<' | MAYORIGUAL='>=' | MENORIGUAL='<=' | AND='&&' |
		//	OR='||';
		public EnumRule getRule() { return rule; }
		
		//IGUAL_IGUAL='==' | DIFERENTE='!=' | MAYORQUE='>' | MENORQUE='<' | MAYORIGUAL='>=' | MENORIGUAL='<=' | AND='&&' | OR='||'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IGUAL_IGUAL='=='
		public EnumLiteralDeclaration getIGUAL_IGUALEnumLiteralDeclaration_0() { return cIGUAL_IGUALEnumLiteralDeclaration_0; }
		
		//'=='
		public Keyword getIGUAL_IGUALEqualsSignEqualsSignKeyword_0_0() { return cIGUAL_IGUALEqualsSignEqualsSignKeyword_0_0; }
		
		//DIFERENTE='!='
		public EnumLiteralDeclaration getDIFERENTEEnumLiteralDeclaration_1() { return cDIFERENTEEnumLiteralDeclaration_1; }
		
		//'!='
		public Keyword getDIFERENTEExclamationMarkEqualsSignKeyword_1_0() { return cDIFERENTEExclamationMarkEqualsSignKeyword_1_0; }
		
		//MAYORQUE='>'
		public EnumLiteralDeclaration getMAYORQUEEnumLiteralDeclaration_2() { return cMAYORQUEEnumLiteralDeclaration_2; }
		
		//'>'
		public Keyword getMAYORQUEGreaterThanSignKeyword_2_0() { return cMAYORQUEGreaterThanSignKeyword_2_0; }
		
		//MENORQUE='<'
		public EnumLiteralDeclaration getMENORQUEEnumLiteralDeclaration_3() { return cMENORQUEEnumLiteralDeclaration_3; }
		
		//'<'
		public Keyword getMENORQUELessThanSignKeyword_3_0() { return cMENORQUELessThanSignKeyword_3_0; }
		
		//MAYORIGUAL='>='
		public EnumLiteralDeclaration getMAYORIGUALEnumLiteralDeclaration_4() { return cMAYORIGUALEnumLiteralDeclaration_4; }
		
		//'>='
		public Keyword getMAYORIGUALGreaterThanSignEqualsSignKeyword_4_0() { return cMAYORIGUALGreaterThanSignEqualsSignKeyword_4_0; }
		
		//MENORIGUAL='<='
		public EnumLiteralDeclaration getMENORIGUALEnumLiteralDeclaration_5() { return cMENORIGUALEnumLiteralDeclaration_5; }
		
		//'<='
		public Keyword getMENORIGUALLessThanSignEqualsSignKeyword_5_0() { return cMENORIGUALLessThanSignEqualsSignKeyword_5_0; }
		
		//AND='&&'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_6() { return cANDEnumLiteralDeclaration_6; }
		
		//'&&'
		public Keyword getANDAmpersandAmpersandKeyword_6_0() { return cANDAmpersandAmpersandKeyword_6_0; }
		
		//OR='||'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_7() { return cOREnumLiteralDeclaration_7; }
		
		//'||'
		public Keyword getORVerticalLineVerticalLineKeyword_7_0() { return cORVerticalLineVerticalLineKeyword_7_0; }
	}
	public class OperadorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.Operador");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMASEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMASPlusSignKeyword_0_0 = (Keyword)cMASEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMENOSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMENOSHyphenMinusKeyword_1_0 = (Keyword)cMENOSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPRODUCTOEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPRODUCTOAsteriskKeyword_2_0 = (Keyword)cPRODUCTOEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDIVISIONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDIVISIONSolidusKeyword_3_0 = (Keyword)cDIVISIONEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cIGUALEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cIGUALEqualsSignKeyword_4_0 = (Keyword)cIGUALEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cGETEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cGETGETKeyword_5_0 = (Keyword)cGETEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDELETEEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDELETEDELETEKeyword_6_0 = (Keyword)cDELETEEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Operador:
		//	MAS='+' | MENOS='-' | PRODUCTO='*' | DIVISION='/' | IGUAL='=' | GET | DELETE;
		public EnumRule getRule() { return rule; }
		
		//MAS='+' | MENOS='-' | PRODUCTO='*' | DIVISION='/' | IGUAL='=' | GET | DELETE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MAS='+'
		public EnumLiteralDeclaration getMASEnumLiteralDeclaration_0() { return cMASEnumLiteralDeclaration_0; }
		
		//'+'
		public Keyword getMASPlusSignKeyword_0_0() { return cMASPlusSignKeyword_0_0; }
		
		//MENOS='-'
		public EnumLiteralDeclaration getMENOSEnumLiteralDeclaration_1() { return cMENOSEnumLiteralDeclaration_1; }
		
		//'-'
		public Keyword getMENOSHyphenMinusKeyword_1_0() { return cMENOSHyphenMinusKeyword_1_0; }
		
		//PRODUCTO='*'
		public EnumLiteralDeclaration getPRODUCTOEnumLiteralDeclaration_2() { return cPRODUCTOEnumLiteralDeclaration_2; }
		
		//'*'
		public Keyword getPRODUCTOAsteriskKeyword_2_0() { return cPRODUCTOAsteriskKeyword_2_0; }
		
		//DIVISION='/'
		public EnumLiteralDeclaration getDIVISIONEnumLiteralDeclaration_3() { return cDIVISIONEnumLiteralDeclaration_3; }
		
		//'/'
		public Keyword getDIVISIONSolidusKeyword_3_0() { return cDIVISIONSolidusKeyword_3_0; }
		
		//IGUAL='='
		public EnumLiteralDeclaration getIGUALEnumLiteralDeclaration_4() { return cIGUALEnumLiteralDeclaration_4; }
		
		//'='
		public Keyword getIGUALEqualsSignKeyword_4_0() { return cIGUALEqualsSignKeyword_4_0; }
		
		//GET
		public EnumLiteralDeclaration getGETEnumLiteralDeclaration_5() { return cGETEnumLiteralDeclaration_5; }
		
		//'GET'
		public Keyword getGETGETKeyword_5_0() { return cGETGETKeyword_5_0; }
		
		//DELETE
		public EnumLiteralDeclaration getDELETEEnumLiteralDeclaration_6() { return cDELETEEnumLiteralDeclaration_6; }
		
		//'DELETE'
		public Keyword getDELETEDELETEKeyword_6_0() { return cDELETEDELETEKeyword_6_0; }
	}
	public class TipoCondicionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.TipoCondicion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cIFEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cIFIfKeyword_0_0 = (Keyword)cIFEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cELSEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cELSEElseKeyword_1_0 = (Keyword)cELSEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum TipoCondicion:
		//	IF='if' | ELSE='else';
		public EnumRule getRule() { return rule; }
		
		//IF='if' | ELSE='else'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IF='if'
		public EnumLiteralDeclaration getIFEnumLiteralDeclaration_0() { return cIFEnumLiteralDeclaration_0; }
		
		//'if'
		public Keyword getIFIfKeyword_0_0() { return cIFIfKeyword_0_0; }
		
		//ELSE='else'
		public EnumLiteralDeclaration getELSEEnumLiteralDeclaration_1() { return cELSEEnumLiteralDeclaration_1; }
		
		//'else'
		public Keyword getELSEElseKeyword_1_0() { return cELSEElseKeyword_1_0; }
	}
	public class OperadorRelacionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.OperadorRelacion");
		private final EnumLiteralDeclaration cPUNTOEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cPUNTOFullStopKeyword_0 = (Keyword)cPUNTOEnumLiteralDeclaration.eContents().get(0);
		
		//enum OperadorRelacion:
		//	PUNTO='.';
		public EnumRule getRule() { return rule; }
		
		//PUNTO='.'
		public EnumLiteralDeclaration getPUNTOEnumLiteralDeclaration() { return cPUNTOEnumLiteralDeclaration; }
		
		//'.'
		public Keyword getPUNTOFullStopKeyword_0() { return cPUNTOFullStopKeyword_0; }
	}
	public class DatoPrimitivoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uniandes.mdd.aplicacion.blockchain.Blockchain.DatoPrimitivo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGSTRINGKeyword_0_0 = (Keyword)cSTRINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNUMERICOEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNUMERICONUMERICOKeyword_1_0 = (Keyword)cNUMERICOEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBOOLEANBOOLEANKeyword_2_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum DatoPrimitivo:
		//	STRING | NUMERICO | BOOLEAN;
		public EnumRule getRule() { return rule; }
		
		//STRING | NUMERICO | BOOLEAN
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_0() { return cSTRINGEnumLiteralDeclaration_0; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_0_0() { return cSTRINGSTRINGKeyword_0_0; }
		
		//NUMERICO
		public EnumLiteralDeclaration getNUMERICOEnumLiteralDeclaration_1() { return cNUMERICOEnumLiteralDeclaration_1; }
		
		//'NUMERICO'
		public Keyword getNUMERICONUMERICOKeyword_1_0() { return cNUMERICONUMERICOKeyword_1_0; }
		
		//BOOLEAN
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_2() { return cBOOLEANEnumLiteralDeclaration_2; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANBOOLEANKeyword_2_0() { return cBOOLEANBOOLEANKeyword_2_0; }
	}
	
	private final AplicacionElements pAplicacion;
	private final TipoDatoElements pTipoDato;
	private final SentenciaElements pSentencia;
	private final SmartContractElements pSmartContract;
	private final EStringElements pEString;
	private final EntidadElements pEntidad;
	private final OperacionElements pOperacion;
	private final EstadoElements pEstado;
	private final AtributoElements pAtributo;
	private final ParametroElements pParametro;
	private final EBooleanElements pEBoolean;
	private final ExpresionLogicaElements pExpresionLogica;
	private final ExpresionAritmeticaElements pExpresionAritmetica;
	private final VariableElements pVariable;
	private final CondicionalElements pCondicional;
	private final ExpresionNumericaElements pExpresionNumerica;
	private final ExpresionTextoElements pExpresionTexto;
	private final ExpresionBooleanElements pExpresionBoolean;
	private final ExpresionReferenciadaElements pExpresionReferenciada;
	private final ExpresionRelacionalElements pExpresionRelacional;
	private final EIntElements pEInt;
	private final OperadorLogicoElements eOperadorLogico;
	private final OperadorElements eOperador;
	private final TipoCondicionElements eTipoCondicion;
	private final EDoubleElements pEDouble;
	private final OperadorRelacionElements eOperadorRelacion;
	private final PrimitivoElements pPrimitivo;
	private final MapaElements pMapa;
	private final DatoPrimitivoElements eDatoPrimitivo;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BlockchainGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAplicacion = new AplicacionElements();
		this.pTipoDato = new TipoDatoElements();
		this.pSentencia = new SentenciaElements();
		this.pSmartContract = new SmartContractElements();
		this.pEString = new EStringElements();
		this.pEntidad = new EntidadElements();
		this.pOperacion = new OperacionElements();
		this.pEstado = new EstadoElements();
		this.pAtributo = new AtributoElements();
		this.pParametro = new ParametroElements();
		this.pEBoolean = new EBooleanElements();
		this.pExpresionLogica = new ExpresionLogicaElements();
		this.pExpresionAritmetica = new ExpresionAritmeticaElements();
		this.pVariable = new VariableElements();
		this.pCondicional = new CondicionalElements();
		this.pExpresionNumerica = new ExpresionNumericaElements();
		this.pExpresionTexto = new ExpresionTextoElements();
		this.pExpresionBoolean = new ExpresionBooleanElements();
		this.pExpresionReferenciada = new ExpresionReferenciadaElements();
		this.pExpresionRelacional = new ExpresionRelacionalElements();
		this.pEInt = new EIntElements();
		this.eOperadorLogico = new OperadorLogicoElements();
		this.eOperador = new OperadorElements();
		this.eTipoCondicion = new TipoCondicionElements();
		this.pEDouble = new EDoubleElements();
		this.eOperadorRelacion = new OperadorRelacionElements();
		this.pPrimitivo = new PrimitivoElements();
		this.pMapa = new MapaElements();
		this.eDatoPrimitivo = new DatoPrimitivoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uniandes.mdd.aplicacion.blockchain.Blockchain".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Aplicacion:
	//	{Aplicacion}
	//	'Aplicacion'
	//	name=EString
	//	'{' (smartcontract+=SmartContract ("," smartcontract+=SmartContract)*)? ('TipoDato' tipodato+=TipoDato (","
	//	tipodato+=TipoDato)*)*
	//	'}';
	public AplicacionElements getAplicacionAccess() {
		return pAplicacion;
	}
	
	public ParserRule getAplicacionRule() {
		return getAplicacionAccess().getRule();
	}
	
	//TipoDato:
	//	Entidad | Primitivo | Mapa;
	public TipoDatoElements getTipoDatoAccess() {
		return pTipoDato;
	}
	
	public ParserRule getTipoDatoRule() {
		return getTipoDatoAccess().getRule();
	}
	
	//Sentencia:
	//	Parametro | Estado | ExpresionLogica | ExpresionAritmetica | Variable | Condicional | ExpresionNumerica | EString |
	//	EBoolean | ExpresionReferenciada | ExpresionRelacional;
	public SentenciaElements getSentenciaAccess() {
		return pSentencia;
	}
	
	public ParserRule getSentenciaRule() {
		return getSentenciaAccess().getRule();
	}
	
	//SmartContract:
	//	'SmartContract'
	//	name=EString
	//	'{' (entidades+=Entidad entidades+=Entidad*)* (estado+=Estado ("," estado+=Estado)*)* (operaciones+=Operacion (","
	//	operaciones+=Operacion)*)*
	//	'}';
	public SmartContractElements getSmartContractAccess() {
		return pSmartContract;
	}
	
	public ParserRule getSmartContractRule() {
		return getSmartContractAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Entidad:
	//	{Entidad}
	//	'Entidad'
	//	name=EString
	//	'{' (atributos+=Atributo atributos+=Atributo*)*
	//	'}';
	public EntidadElements getEntidadAccess() {
		return pEntidad;
	}
	
	public ParserRule getEntidadRule() {
		return getEntidadAccess().getRule();
	}
	
	//Operacion:
	//	{Operacion}
	//	'Operacion' ('isUd=' esUserDefined?=EBoolean)+
	//	name=EString
	//	'(' (parametros+=Parametro ("," parametros+=Parametro)*)?
	//	')' (':' retorno=[TipoDato|EString])?
	//	'{'
	//	'return'? (sentencia+=Sentencia sentencia+=Sentencia*)?
	//	'}';
	public OperacionElements getOperacionAccess() {
		return pOperacion;
	}
	
	public ParserRule getOperacionRule() {
		return getOperacionAccess().getRule();
	}
	
	//Estado:
	//	'Estado'
	//	tipodato=[TipoDato] name=EString;
	public EstadoElements getEstadoAccess() {
		return pEstado;
	}
	
	public ParserRule getEstadoRule() {
		return getEstadoAccess().getRule();
	}
	
	//Atributo:
	//	tipodato=[TipoDato|EString] name=EString;
	public AtributoElements getAtributoAccess() {
		return pAtributo;
	}
	
	public ParserRule getAtributoRule() {
		return getAtributoAccess().getRule();
	}
	
	//Parametro:
	//	tipodato=[TipoDato|EString] name=EString;
	public ParametroElements getParametroAccess() {
		return pParametro;
	}
	
	public ParserRule getParametroRule() {
		return getParametroAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//ExpresionLogica:
	//	'ExpLog'
	//	'('? ('id' id=EInt)?
	//	ladoIzq=[Sentencia|EString] operador=OperadorLogico+
	//	ladoDer=[Sentencia|EString] ')'?;
	public ExpresionLogicaElements getExpresionLogicaAccess() {
		return pExpresionLogica;
	}
	
	public ParserRule getExpresionLogicaRule() {
		return getExpresionLogicaAccess().getRule();
	}
	
	//ExpresionAritmetica:
	//	{ExpresionAritmetica} ('id' id=EInt)?
	//	ladoIzq=[Sentencia|EString] operador=Operador+
	//	ladoDer=[Sentencia|EString];
	public ExpresionAritmeticaElements getExpresionAritmeticaAccess() {
		return pExpresionAritmetica;
	}
	
	public ParserRule getExpresionAritmeticaRule() {
		return getExpresionAritmeticaAccess().getRule();
	}
	
	//Variable:
	//	{Variable} tipodato=[TipoDato|EString]
	//	'var'
	//	name=EString;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Condicional:
	//	'Condicional'
	//	'{' ('tipoCondicional' tipoCondicional=TipoCondicion)?
	//	'expresionlogica' expresionlogica=ExpresionLogica
	//	'sentencias' '{' sentencias+=Sentencia ("," sentencias+=Sentencia)* '}' ('else' '{' else+=Condicional (","
	//	else+=Condicional)* '}')?
	//	'}';
	public CondicionalElements getCondicionalAccess() {
		return pCondicional;
	}
	
	public ParserRule getCondicionalRule() {
		return getCondicionalAccess().getRule();
	}
	
	//ExpresionNumerica:
	//	{ExpresionNumerica}
	//	'ExpNum'
	//	value=EDouble?;
	public ExpresionNumericaElements getExpresionNumericaAccess() {
		return pExpresionNumerica;
	}
	
	public ParserRule getExpresionNumericaRule() {
		return getExpresionNumericaAccess().getRule();
	}
	
	//ExpresionTexto:
	//	{ExpresionTexto}
	//	'ExpText'
	//	'{' ('value' value=EString)?
	//	'}';
	public ExpresionTextoElements getExpresionTextoAccess() {
		return pExpresionTexto;
	}
	
	public ParserRule getExpresionTextoRule() {
		return getExpresionTextoAccess().getRule();
	}
	
	//ExpresionBoolean:
	//	{ExpresionBoolean} value?='value'?
	//	'ExpBool';
	public ExpresionBooleanElements getExpresionBooleanAccess() {
		return pExpresionBoolean;
	}
	
	public ParserRule getExpresionBooleanRule() {
		return getExpresionBooleanAccess().getRule();
	}
	
	//ExpresionReferenciada:
	//	{ExpresionReferenciada}
	//	'ExpRef' ('id' id=EInt)?
	//	entReferenciada=[Entidad|EString]?
	//	atrReferenciado=[Atributo|EString]?;
	public ExpresionReferenciadaElements getExpresionReferenciadaAccess() {
		return pExpresionReferenciada;
	}
	
	public ParserRule getExpresionReferenciadaRule() {
		return getExpresionReferenciadaAccess().getRule();
	}
	
	//ExpresionRelacional:
	//	'ExpRel'
	//	'{' ('id' id=EInt)?
	//	ladoIzq=[Sentencia|EString] operadorRelacional=OperadorRelacion?
	//	ladoDer=[Sentencia|EString]
	//	'}';
	public ExpresionRelacionalElements getExpresionRelacionalAccess() {
		return pExpresionRelacional;
	}
	
	public ParserRule getExpresionRelacionalRule() {
		return getExpresionRelacionalAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum OperadorLogico:
	//	IGUAL_IGUAL='==' | DIFERENTE='!=' | MAYORQUE='>' | MENORQUE='<' | MAYORIGUAL='>=' | MENORIGUAL='<=' | AND='&&' |
	//	OR='||';
	public OperadorLogicoElements getOperadorLogicoAccess() {
		return eOperadorLogico;
	}
	
	public EnumRule getOperadorLogicoRule() {
		return getOperadorLogicoAccess().getRule();
	}
	
	//enum Operador:
	//	MAS='+' | MENOS='-' | PRODUCTO='*' | DIVISION='/' | IGUAL='=' | GET | DELETE;
	public OperadorElements getOperadorAccess() {
		return eOperador;
	}
	
	public EnumRule getOperadorRule() {
		return getOperadorAccess().getRule();
	}
	
	//enum TipoCondicion:
	//	IF='if' | ELSE='else';
	public TipoCondicionElements getTipoCondicionAccess() {
		return eTipoCondicion;
	}
	
	public EnumRule getTipoCondicionRule() {
		return getTipoCondicionAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//enum OperadorRelacion:
	//	PUNTO='.';
	public OperadorRelacionElements getOperadorRelacionAccess() {
		return eOperadorRelacion;
	}
	
	public EnumRule getOperadorRelacionRule() {
		return getOperadorRelacionAccess().getRule();
	}
	
	//Primitivo:
	//	{Primitivo} tipo=DatoPrimitivo+
	//	name=EString;
	public PrimitivoElements getPrimitivoAccess() {
		return pPrimitivo;
	}
	
	public ParserRule getPrimitivoRule() {
		return getPrimitivoAccess().getRule();
	}
	
	//Mapa:
	//	name=EString
	//	':' 'Map'
	//	'<'
	//	tipoDatoKey=[TipoDato|EString]
	//	',' tipoDatoValue=[TipoDato|EString] '>';
	public MapaElements getMapaAccess() {
		return pMapa;
	}
	
	public ParserRule getMapaRule() {
		return getMapaAccess().getRule();
	}
	
	//enum DatoPrimitivo:
	//	STRING | NUMERICO | BOOLEAN;
	public DatoPrimitivoElements getDatoPrimitivoAccess() {
		return eDatoPrimitivo;
	}
	
	public EnumRule getDatoPrimitivoRule() {
		return getDatoPrimitivoAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
