/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBlockchainScopeProvider extends DelegatingScopeProvider {
}
