/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uniandes.mdd.aplicacion.blockchain.parser.antlr.internal.InternalBlockchainParser;
import uniandes.mdd.aplicacion.blockchain.services.BlockchainGrammarAccess;

public class BlockchainParser extends AbstractAntlrParser {

	@Inject
	private BlockchainGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlockchainParser createParser(XtextTokenStream stream) {
		return new InternalBlockchainParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Aplicacion";
	}

	public BlockchainGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BlockchainGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
