/*
 * generated by Xtext 2.12.0
 */
package uniandes.mdd.aplicacion.blockchain.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BlockchainAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uniandes/mdd/aplicacion/blockchain/parser/antlr/internal/InternalBlockchain.tokens");
	}
}
